//Auth
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM'
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM'
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'
export const RESET_AUTH_FORMS = 'RESET_AUTH_FORMS'

//Feedback
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const SUCCESS = 'SUCCESS'

// Workouts
export const LOAD_WROKOUTS = 'LOAD_WORKOUTS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const LOAD_WORKOUT_DETAILS = 'LOAD_DETAIL'
export const SET_WORKOUT_PAGES_COUNT = 'SET_WORKOUT_PAGES_COUNT'
export const CHANGE_WORKOUT_CREATE_FORM = 'CHANGE_WORKOUT_CREATE_FORM'
export const WORKOUT_CREATED = 'WORKOUT_CREATED'
export const RESET_CREATE_WORKOUT_FORM = 'RESET_CREATE_WORKOUT_FORM'
