// Auth
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM'
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM'
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'
export const RESET_AUTH_FORMS = 'RESET_AUTH_FORMS'
export const SET_ADMIN_STATUS = 'SET_ADMIN_STATUS'

// Feedback
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const SUCCESS = 'SUCCESS'

// Workouts
export const LOAD_WROKOUTS = 'LOAD_WORKOUTS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const LOAD_WORKOUT_DETAILS = 'LOAD_DETAIL'
export const SET_WORKOUT_PAGES_COUNT = 'SET_WORKOUT_PAGES_COUNT'
export const CHANGE_WORKOUT_FORM = 'CHANGE_WORKOUT_FORM'
export const WORKOUT_CREATED = 'WORKOUT_CREATED'
export const RESET_WORKOUT_FORM = 'RESET_WORKOUT_FORM'
export const CHANGE_WORKOUTS_COUNT = 'CHANGE_WORKOUTS_COUNT'

// Users
export const CHANGE_PROFILE_DATA = 'CHANGE_PROFILE_DATA'
export const CHANGE_USERS_COUNT = 'CHANGE_USERS_COUNT'

// Admin
export const LOAD_ALL_USERS = 'LOAD_ALL_USERS'
export const CHANGE_USERS_PAGE = 'CHANGE_USERS_PAGE'